// Central source of truth for all seminar content (PRD §5, §6).
// Edit copy, dates, and contact info here once.

export const BRAND = {
  name: "Health & Wealth Legacy",
  tagline: "We Educate • We Empower • We Protect",
  email: "hwlfinancial7@gmail.com",
  website: "healthandwealthlegacy.net",
  websiteUrl: "https://healthandwealthlegacy.net",
  // Reservation line per the seminar brief (PRD §10 open item).
  phoneDisplay: "816-518-1405",
  phoneHref: "tel:+18165181405",
  // Company office (distinct from the seminar venue in LOCATION).
  office: {
    line1: "7280 NW 87th Terrace, Suite 216",
    line2: "Kansas City, MO 64135",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=7280+NW+87th+Terrace+Suite+216+Kansas+City+MO+64135",
  },
} as const;

// Final, public URL — update once the live domain is known (PRD §10, used for
// canonical, Open Graph, JSON-LD, and the footer QR code).
export const SITE_URL = "https://seminar.healthandwealthlegacy.net";

export const HERO = {
  headline: "Complimentary Estate Planning Seminar: Wills & Living Trusts",
  subheadline:
    "Health & Wealth Legacy cordially invites you to attend this free educational seminar and learn how proper estate planning can help protect your family, assets, and legacy.",
  badges: [
    { label: "FREE Educational Seminar", href: "#topics", external: false },
    { label: "Sept 10 & 12, 2026", href: "#register", external: false },
    {
      label: "Gladstone, MO",
      href: "https://www.google.com/maps/search/?api=1&query=Gladstone+Community+Center+6901+N+Holmes+Street+Gladstone+MO+64118",
      external: true,
    },
  ],
  cta: "Reserve Your Free Seat",
} as const;

export const INTRO =
  "An estate plan is vital for individuals, couples, and families who own a home, have savings, retirement accounts, investments, or other assets. Ensure your estate planning is in order by understanding the strategies families use to avoid the delays, expenses, and frustrations associated with Probate Court. Learn practical estate planning techniques designed to help protect your loved ones, preserve your wealth, and transfer assets according to your wishes.";

export const TOPICS_HEADING =
  "You will learn the following topics in easy-to-understand terms:";

export const TOPICS = [
  "The advantages and disadvantages of Wills and Living Trusts",
  "How Powers of Attorney work — and when they may no longer be effective (some may not be valid if you are disabled or pass away)",
  "Common estate planning mistakes affecting families with children who have special needs or disabilities",
  "Understanding the Probate Court process, how it works, and why many families seek to avoid it",
  "Why putting property in your children's names could be a costly mistake",
  "Asset protection and wealth transfer strategies",
  "Protecting your heirs' inheritance from lawsuits, divorce, creditors, and spendthrift issues",
  "Retirement and Long-Term Care planning strategies",
  "Best practices for naming beneficiaries on retirement accounts and life insurance policies",
  "How the SECURE Act may impact your Trust and Retirement Accounts",
] as const;

export const WHY_ATTEND =
  "This seminar is designed to help you and your family avoid some of the most common and costly estate planning mistakes. Be our guest at this unique FREE educational presentation and gain valuable insights that could help protect your family's future.";

export const VIDEO = {
  id: "QJ8zxNgpdBA",
  title: "Why Estate Planning Matters",
  sectionTitle: "Watch: Why Estate Planning Matters",
} as const;

export type ShowcaseVideo = {
  title: string;
  description: string;
  src: string; // Cloudinary MP4 (poster auto-generated by swapping .mp4 → .jpg)
};

export const SHOWCASE_VIDEOS: ShowcaseVideo[] = [
  {
    title: "Free Video Course for Someone You Know",
    description:
      "Think of someone you know over the age of 50 . . . then watch this short video to learn why they will thank you for sharing this free course with them.",
    src: "https://res.cloudinary.com/dkkpuv4ok/video/upload/v1782542480/Free_Video_Course_for_Someone_You_Know_mfmuaj.mp4",
  },
  {
    title: "“End of Life” Legal and Financial Considerations",
    description:
      "If you realize that a fatal accident or illness can end your life at any time, and you don't want to leave your family unprepared, watch this video to learn how important it is to provide instructions and make provisions for the “End of Life.”",
    src: "https://res.cloudinary.com/dkkpuv4ok/video/upload/v1782542645/End_of_Life_Legal_and_Financial_Considerations_jzilzc.mp4",
  },
];

export type Session = {
  id: string;
  label: string; // form option label
  day: string;
  date: string; // ISO start for JSON-LD / calendar
  endDate: string;
  time: string;
};

export const SESSIONS: Session[] = [
  {
    id: "thu-sep-10-12pm",
    label: "Thursday, September 10 — 12:00 PM",
    day: "Thursday, September 10, 2026",
    date: "2026-09-10T12:00:00-05:00",
    endDate: "2026-09-10T13:30:00-05:00",
    time: "12:00 PM",
  },
  {
    id: "thu-sep-10-6pm",
    label: "Thursday, September 10 — 6:00 PM",
    day: "Thursday, September 10, 2026",
    date: "2026-09-10T18:00:00-05:00",
    endDate: "2026-09-10T19:30:00-05:00",
    time: "6:00 PM",
  },
  {
    id: "sat-sep-12-12pm",
    label: "Saturday, September 12 — 12:00 PM",
    day: "Saturday, September 12, 2026",
    date: "2026-09-12T12:00:00-05:00",
    endDate: "2026-09-12T13:30:00-05:00",
    time: "12:00 PM",
  },
];

export const LOCATION = {
  name: "Gladstone Community Center",
  street: "6901 N. Holmes Street",
  city: "Gladstone",
  state: "MO",
  zip: "64118",
  mapsUrl:
    "https://www.google.com/maps/search/?api=1&query=Gladstone+Community+Center+6901+N+Holmes+Street+Gladstone+MO+64118",
} as const;

export const SPEAKER = {
  name: "Brian Beazly",
  bio: "Owning and operating a business for more than 30 years, Brian Beazly saw the need many people have for help with retirement income and estate planning strategies. In 2011, Brian began working with families in Indiana and Kentucky in the areas of end-of-life preparation and wealth transfer. Brian is a licensed health and life agent in Kentucky, Indiana and several other states. He was a flight instructor for many years. His spirit of teaching carries forward in helping people understand and implement the best wealth strategies for their families.",
} as const;

export const DISCLOSURE = [
  "This seminar is not sponsored by the Gladstone Community Center, and the Gladstone Community Center does not endorse any views expressed by the sponsors of this event.",
  "The information presented during this seminar is for educational purposes only and does not constitute legal, tax, or financial advice. It is not intended to replace consultation with qualified legal counsel or other professional advisors.",
  "If you have specific legal questions following the seminar, we will be happy to connect you with our team and a qualified estate planning attorney.",
] as const;

export const INTERESTS = [
  "Estate Planning",
  "Living Trust",
  "Retirement Planning",
  "Long-Term Care Planning",
  "Asset Protection",
] as const;

export type Partner = { name: string; src: string };

export const PARTNERS: Partner[] = [
  { name: "Mediator Debt Solutions", src: "/images/partner-mediator.jpg" },
  { name: "Tristate Financial Network", src: "/images/partner-tristate.jpg" },
  { name: "Integrity Wealth", src: "/images/partner-integrity-wealth.jpg" },
  { name: "The Alliance", src: "/images/partner-alliance.jpg" },
  { name: "Dadkhah Law Group", src: "/images/partner-dadkhah-law.jpg" },
  { name: "Integrated Trust Systems", src: "/images/partner-integrated-trust.jpg" },
];

export const LOGO_SRC = "/images/logo.jpg";
export const SPEAKER_PHOTO = "/images/speaker.png";
